spring:
  #data source to store user credentials
  datasource-auth:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/viola-auth
    username: postgres
    password: password
  #data source to store user credentials
  datasource-main:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/viola-main
      username: postgres
      password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true